### ISSUE TITLE
401 Uninitialised session

### ISSUE THREAD

**Issue by dtitov** [CSCfi/oidc-client#15]
#### Describe the bug
In a local setup, I get `401 Uninitialised session` after successful authentication and redirect back. 

#### To Reproduce
Steps to reproduce the behaviour:
1. Login through Elixir AAI.
2. Get redirected back.
3. Behold `401 Uninitialised session` error.

#### Expected behavior
Authentication worked successfully. 

#### Screenshots
![](https://habrastorage.org/webt/p1/gw/0i/p1gw0icsk2yo85hn0dlcmgqf4cg.png)

#### Additional context
- MacOS
- Python 3.7.5

**Comment by teemukataja** [comment]
This issue emerges, when running the web app in `localhost`, the issue is averted when the web app has a domain name (is deployed to a server). This is somehow a feature of the `aiohttp` module that this web app is built with.

This issue happens because:
1. When the web app receives a `/login` it generates a state id, which it stores to the browser cookies in the domain that the web app is running at
2. Then the web app will send the user to the AAI, along with the state id it stored, to authenticate the user
3. When the AAI returns the user to the web app at `/callback`, it sends the state id back
4. Here the web app compares the received state id to the one stored in the browser cookies
5. Because the cookies don't exist, this `401 Uninitialised Session` response is given (you also get this if you try to go to `/callback` directly

It was designed like this, because it was simple and didn't need any additional session storage to be set up, and we only intend to run this web app deployed to a server with a domain name.
